// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TradingBot.Persistence;

#nullable disable

namespace TradingBot.Persistence.Migrations
{
    [DbContext(typeof(TradingBotDbContext))]
    partial class TradingBotDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("TradingBot.Persistence.AiAnalysisRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Context")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgentType");

                    b.HasIndex("Model");

                    b.HasIndex("PromptVersion");

                    b.HasIndex("TimestampUtc");

                    b.ToTable("AiAnalysisRecords");
                });

            modelBuilder.Entity("TradingBot.Persistence.AiApiUsageRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("CachedInputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FailureReason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("InputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("OutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TotalTokens")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AgentType");

                    b.HasIndex("Model");

                    b.HasIndex("Pattern");

                    b.HasIndex("PromptVersion");

                    b.HasIndex("RequestType");

                    b.HasIndex("Success");

                    b.HasIndex("Symbol");

                    b.HasIndex("TimestampUtc");

                    b.ToTable("AiApiUsageRecords");
                });

            modelBuilder.Entity("TradingBot.Persistence.BotSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StoppedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BotSessions");
                });

            modelBuilder.Entity("TradingBot.Persistence.Candle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Close")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("High")
                        .HasColumnType("TEXT");

                    b.Property<string>("InstrumentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFinal")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Low")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Open")
                        .HasColumnType("TEXT");

                    b.Property<int>("QualityStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReceivedTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Timeframe")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Volume")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentId");

                    b.HasIndex("QualityStatus");

                    b.HasIndex("ReceivedTimeUtc");

                    b.HasIndex("Symbol", "Timeframe", "TimestampUtc")
                        .IsUnique();

                    b.ToTable("Candles");
                });

            modelBuilder.Entity("TradingBot.Persistence.ExitManagementRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BreakEvenActivated")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ClosedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntryBrokerOrderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FilledQuantity")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HighestPriceSinceEntry")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InitialEntryPrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InitialRiskPerShare")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InitialStopPrice")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OpenedUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrentProtectiveStop")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ProtectedQuantity")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProtectiveStopBrokerOrderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("TrailingActivated")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TrailingAtrMultiplier")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrailingAtrTimeframe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TradeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EntryBrokerOrderId")
                        .IsUnique();

                    b.HasIndex("ProtectiveStopBrokerOrderId");

                    b.HasIndex("State");

                    b.HasIndex("Symbol");

                    b.HasIndex("UpdatedUtc");

                    b.ToTable("ExitManagementRecords");
                });

            modelBuilder.Entity("TradingBot.Persistence.ExitStopAuditRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrokerOrderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CurrentAtr")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrentRMultiple")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntryBrokerOrderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExitManagementState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HighestPriceSinceEntry")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MarketPrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NewStop")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("OldStop")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TradeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BrokerOrderId");

                    b.HasIndex("EntryBrokerOrderId");

                    b.HasIndex("Symbol");

                    b.HasIndex("TimestampUtc");

                    b.HasIndex("TradeId");

                    b.ToTable("ExitStopAuditRecords");
                });

            modelBuilder.Entity("TradingBot.Persistence.ExecutionRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrokerExecutionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderRecordId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BrokerExecutionId")
                        .IsUnique();

                    b.ToTable("ExecutionRecords");
                });

            modelBuilder.Entity("TradingBot.Persistence.HistoricalBackfillJobRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("BarsInserted").HasColumnType("INTEGER");
                    b.Property<long>("BarsReceived").HasColumnType("INTEGER");
                    b.Property<int>("CompletedSegments").HasColumnType("INTEGER");
                    b.Property<DateTime>("CreatedAtUtc").HasColumnType("TEXT");
                    b.Property<DateTime>("DesiredEndUtc").HasColumnType("TEXT");
                    b.Property<DateTime>("DesiredStartUtc").HasColumnType("TEXT");
                    b.Property<long>("DuplicateBars").HasColumnType("INTEGER");
                    b.Property<int>("FailedAttempts").HasColumnType("INTEGER");
                    b.Property<int>("GapCount").HasColumnType("INTEGER");
                    b.Property<string>("InstrumentId").IsRequired().HasColumnType("TEXT").UseCollation("NOCASE");
                    b.Property<string>("LastError").IsRequired().HasColumnType("TEXT");
                    b.Property<DateTime?>("LastRequestedAtUtc").HasColumnType("TEXT");
                    b.Property<DateTime?>("NextAttemptUtc").HasColumnType("TEXT");
                    b.Property<DateTime>("NextSegmentEndUtc").HasColumnType("TEXT");
                    b.Property<int>("Status").HasColumnType("INTEGER");
                    b.Property<string>("Symbol").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("Timeframe").IsRequired().HasColumnType("TEXT").UseCollation("NOCASE");
                    b.Property<DateTime>("UpdatedAtUtc").HasColumnType("TEXT");
                    b.Property<int>("Version").IsConcurrencyToken().HasColumnType("INTEGER");

                    b.HasKey("Id");
                    b.HasIndex("NextAttemptUtc");
                    b.HasIndex("Status");
                    b.HasIndex("UpdatedAtUtc");
                    b.HasIndex("InstrumentId", "Timeframe").IsUnique();
                    b.ToTable("HistoricalBackfillJobRecords");
                });

            modelBuilder.Entity("TradingBot.Persistence.HistoricalBackfillSegmentRecord", b =>
                {
                    b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<int>("AttemptCount").HasColumnType("INTEGER");
                    b.Property<int>("BarsInserted").HasColumnType("INTEGER");
                    b.Property<int>("BarsReceived").HasColumnType("INTEGER");
                    b.Property<DateTime?>("CompletedAtUtc").HasColumnType("TEXT");
                    b.Property<int>("DuplicateBars").HasColumnType("INTEGER");
                    b.Property<DateTime>("EndUtc").HasColumnType("TEXT");
                    b.Property<string>("InstrumentId").IsRequired().HasColumnType("TEXT");
                    b.Property<long>("JobId").HasColumnType("INTEGER");
                    b.Property<string>("LastError").IsRequired().HasColumnType("TEXT");
                    b.Property<DateTime>("RequestedAtUtc").HasColumnType("TEXT");
                    b.Property<DateTime>("StartUtc").HasColumnType("TEXT");
                    b.Property<int>("Status").HasColumnType("INTEGER");
                    b.Property<string>("Symbol").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("Timeframe").IsRequired().HasColumnType("TEXT");

                    b.HasKey("Id");
                    b.HasIndex("InstrumentId");
                    b.HasIndex("RequestedAtUtc");
                    b.HasIndex("Status");
                    b.HasIndex("JobId", "StartUtc", "EndUtc").IsUnique();
                    b.ToTable("HistoricalBackfillSegmentRecords");
                });

            modelBuilder.Entity("TradingBot.Persistence.HistoricalDataGapRecord", b =>
                {
                    b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<DateTime>("DetectedAtUtc").HasColumnType("TEXT");
                    b.Property<DateTime>("EndUtc").HasColumnType("TEXT");
                    b.Property<string>("InstrumentId").IsRequired().HasColumnType("TEXT");
                    b.Property<long>("JobId").HasColumnType("INTEGER");
                    b.Property<int>("MissingBars").HasColumnType("INTEGER");
                    b.Property<DateTime>("StartUtc").HasColumnType("TEXT");
                    b.Property<string>("Symbol").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("Timeframe").IsRequired().HasColumnType("TEXT");

                    b.HasKey("Id");
                    b.HasIndex("DetectedAtUtc");
                    b.HasIndex("InstrumentId");
                    b.HasIndex("JobId", "StartUtc", "EndUtc").IsUnique();
                    b.ToTable("HistoricalDataGapRecords");
                });

            modelBuilder.Entity("TradingBot.Persistence.InstrumentRegistryRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AllowedDirectionsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("BrokerContractId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrokerPrimaryExchange")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigurationHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ConfiguredEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InstrumentId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("MarketDataTimeframesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaximumHoldingSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("MaximumPositionValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecurityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StatusChangedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusReason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StrategyIdsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("TradingRequested")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ConfiguredEnabled");

                    b.HasIndex("InstrumentId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("Symbol");

                    b.HasIndex("UpdatedAtUtc");

                    b.ToTable("InstrumentRegistryRecords");
                });

            modelBuilder.Entity("TradingBot.Persistence.InstrumentStatusTransitionRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FromStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InstrumentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ToStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentId");

                    b.HasIndex("TimestampUtc");

                    b.HasIndex("ToStatus");

                    b.ToTable("InstrumentStatusTransitionRecords");
                });

            modelBuilder.Entity("TradingBot.Persistence.MarketDataQualityIncidentRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EventTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("InstrumentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReceivedTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StreamKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Timeframe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("InstrumentId");

                    b.HasIndex("RecordedAtUtc");

                    b.HasIndex("Status");

                    b.HasIndex("StreamKey");

                    b.ToTable("MarketDataQualityIncidentRecords");
                });

            modelBuilder.Entity("TradingBot.Persistence.MarketDataStreamStateRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("InstrumentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsHealthy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastEventId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastEventTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastReceivedTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastSequence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StatusReason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StreamKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Timeframe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentId");

                    b.HasIndex("Status");

                    b.HasIndex("StreamKey")
                        .IsUnique();

                    b.HasIndex("UpdatedAtUtc");

                    b.ToTable("MarketDataStreamStateRecords");
                });

            modelBuilder.Entity("TradingBot.Persistence.MarketSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MarketSnapshots");
                });

            modelBuilder.Entity("TradingBot.Persistence.OrderRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrokerOrderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientOrderKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BrokerOrderId");

                    b.HasIndex("ClientOrderKey")
                        .IsUnique()
                        .HasFilter("ClientOrderKey <> ''");

                    b.ToTable("OrderRecords");
                });

            modelBuilder.Entity("TradingBot.Persistence.PatternDetection", b =>
                {
                    b.Property<int>("Direction")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("InstrumentId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("PatternKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PatternVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SignalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StrategyId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DetectedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("PatternType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Timeframe")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PatternType");

                    b.HasIndex("InstrumentId");

                    b.HasIndex("PatternKey")
                        .IsUnique()
                        .HasFilter("PatternKey <> ''");

                    b.HasIndex("SignalId");

                    b.HasIndex("Symbol");

                    b.HasIndex("InstrumentId", "StrategyId", "Timeframe", "Direction", "DetectedAtUtc");

                    b.ToTable("PatternDetections");
                });

            modelBuilder.Entity("TradingBot.Persistence.PostTradeAnalysisRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("AboveVwap")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AiCriticAnalysisJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("AiConfidence")
                        .HasColumnType("TEXT");

                    b.Property<string>("AiDecision")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AiMarketAnalysisJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CommissionsFees")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ClosedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CriticDecision")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EntryPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutionDataJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ExitPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("FifteenMinuteTrend")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GrossProfitLoss")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HoldingDurationMinutes")
                        .HasColumnType("TEXT");

                    b.Property<string>("MarketRegime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MarketSnapshotJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MaximumAdverseExcursion")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MaximumFavorableExcursion")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NetProfitLoss")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OpenedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderDataJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PatternCandidateJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<string>("RiskDecision")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RiskDecisionJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SourceTradeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StrategyDecision")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StrategyDecisionJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TradeResult")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TradeResultJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AboveVwap");

                    b.HasIndex("AiDecision");

                    b.HasIndex("ClosedUtc");

                    b.HasIndex("FifteenMinuteTrend");

                    b.HasIndex("MarketRegime");

                    b.HasIndex("Pattern");

                    b.HasIndex("SourceTradeId");

                    b.HasIndex("Symbol");

                    b.ToTable("PostTradeAnalysisRecords");
                });

            modelBuilder.Entity("TradingBot.Persistence.ReplayRunRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CheckpointEventTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CheckpointEventId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CheckpointReceivedTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FeatureVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FromUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("InputSha256")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("InputEventCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InstrumentId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("LastError")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MarketDataVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputSha256")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PatternVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProcessedEventCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SignalCount")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SpeedMultiplier")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StrategyId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StrategyVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ToUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("InstrumentId");

                    b.HasIndex("Status");

                    b.HasIndex("UpdatedAtUtc");

                    b.ToTable("ReplayRunRecords");
                });

            modelBuilder.Entity("TradingBot.Persistence.ReplaySignalRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Confidence")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DetectedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Direction")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FeaturesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PatternType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RelevantPriceLevelsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ReplayRunId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SignalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceEventId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Timeframe")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SourceEventId");

                    b.HasIndex("ReplayRunId", "DetectedAtUtc");

                    b.HasIndex("ReplayRunId", "SignalId")
                        .IsUnique();

                    b.ToTable("ReplaySignalRecords");
                });

            modelBuilder.Entity("TradingBot.Persistence.ResearchCandidateRecord", b =>
                {
                    b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<string>("CandidateKey").IsRequired().HasColumnType("TEXT");
                    b.Property<decimal>("Confidence").HasColumnType("TEXT");
                    b.Property<DateTime>("CreatedAtUtc").HasColumnType("TEXT");
                    b.Property<string>("DecisionStage").IsRequired().HasColumnType("TEXT");
                    b.Property<int>("Direction").HasColumnType("INTEGER");
                    b.Property<DateTime>("EvaluatedAtUtc").HasColumnType("TEXT");
                    b.Property<string>("FeatureVersion").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("HardConditionsJson").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("InstrumentId").IsRequired().HasColumnType("TEXT").UseCollation("NOCASE");
                    b.Property<string>("LabelVersion").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("MarketRegime").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("MetadataJson").IsRequired().HasColumnType("TEXT");
                    b.Property<decimal?>("NormalizedLiquidity").HasColumnType("TEXT");
                    b.Property<decimal?>("NormalizedVolatility").HasColumnType("TEXT");
                    b.Property<int>("Outcome").HasColumnType("INTEGER");
                    b.Property<int>("PatternType").HasColumnType("INTEGER");
                    b.Property<string>("PatternVersion").IsRequired().HasColumnType("TEXT");
                    b.Property<decimal>("ReferencePrice").HasColumnType("TEXT");
                    b.Property<string>("ReasonsJson").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("RecordKey").IsRequired().HasColumnType("TEXT");
                    b.Property<Guid?>("ReplayRunId").HasColumnType("TEXT");
                    b.Property<string>("ScoreComponentsJson").IsRequired().HasColumnType("TEXT");
                    b.Property<Guid?>("SignalId").HasColumnType("TEXT");
                    b.Property<string>("SourceEventId").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("StrategyId").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("Symbol").IsRequired().HasColumnType("TEXT");
                    b.Property<int>("Timeframe").HasColumnType("INTEGER");
                    b.Property<DateTime>("UpdatedAtUtc").HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("CandidateKey");
                    b.HasIndex("InstrumentId");
                    b.HasIndex("Outcome");
                    b.HasIndex("RecordKey").IsUnique();
                    b.HasIndex("ReplayRunId");
                    b.HasIndex("InstrumentId", "StrategyId", "Timeframe", "Direction", "EvaluatedAtUtc");
                    b.ToTable("ResearchCandidateRecords");
                });

            modelBuilder.Entity("TradingBot.Persistence.CandidateLabelRecord", b =>
                {
                    b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<DateTime?>("CalculatedAtUtc").HasColumnType("TEXT");
                    b.Property<decimal>("EntryPrice").HasColumnType("TEXT");
                    b.Property<decimal?>("EstimatedCostBps").HasColumnType("TEXT");
                    b.Property<decimal?>("ExitPrice").HasColumnType("TEXT");
                    b.Property<string>("FirstStopEventId").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("FirstTargetEventId").IsRequired().HasColumnType("TEXT");
                    b.Property<decimal?>("GrossReturnBps").HasColumnType("TEXT");
                    b.Property<int>("HorizonSeconds").HasColumnType("INTEGER");
                    b.Property<string>("LabelVersion").IsRequired().HasColumnType("TEXT");
                    b.Property<decimal?>("MaximumAdverseExcursionBps").HasColumnType("TEXT");
                    b.Property<DateTime?>("MaximumEventTimeUtc").HasColumnType("TEXT");
                    b.Property<decimal?>("MaximumFavorableExcursionBps").HasColumnType("TEXT");
                    b.Property<decimal?>("NetReturnBps").HasColumnType("TEXT");
                    b.Property<int>("ObservationCount").HasColumnType("INTEGER");
                    b.Property<decimal?>("ObservedSpreadBps").HasColumnType("TEXT");
                    b.Property<string>("ReasonsJson").IsRequired().HasColumnType("TEXT");
                    b.Property<long>("ResearchCandidateId").HasColumnType("INTEGER");
                    b.Property<int>("Status").HasColumnType("INTEGER");
                    b.Property<int>("TargetStopOutcome").HasColumnType("INTEGER");
                    b.Property<DateTime>("WindowEndUtc").HasColumnType("TEXT");
                    b.Property<DateTime>("WindowStartUtc").HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("ResearchCandidateId", "HorizonSeconds").IsUnique();
                    b.HasIndex("Status", "WindowEndUtc");
                    b.ToTable("CandidateLabelRecords");
                });

            modelBuilder.Entity("TradingBot.Persistence.ResearchEvaluationRunRecord", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");
                    b.Property<DateTime>("CompletedAtUtc").HasColumnType("TEXT");
                    b.Property<string>("CostSensitivityJson").IsRequired().HasColumnType("TEXT");
                    b.Property<DateTime>("CreatedAtUtc").HasColumnType("TEXT");
                    b.Property<int>("EligibleCandidateCount").HasColumnType("INTEGER");
                    b.Property<string>("EvaluationVersion").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("FeatureVersion").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("FoldsJson").IsRequired().HasColumnType("TEXT");
                    b.Property<DateTime>("FromUtc").HasColumnType("TEXT");
                    b.Property<int>("HorizonSeconds").HasColumnType("INTEGER");
                    b.Property<DateTime>("HoldoutStartUtc").HasColumnType("TEXT");
                    b.Property<string>("HoldoutMetricsJson").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("InputSha256").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("InstrumentId").IsRequired().HasColumnType("TEXT").UseCollation("NOCASE");
                    b.Property<string>("LabelVersion").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("OutputSha256").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("PatternVersion").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("PreHoldoutMetricsJson").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("PreHoldoutThresholdsJson").IsRequired().HasColumnType("TEXT");
                    b.Property<Guid?>("ReplayRunId").HasColumnType("TEXT");
                    b.Property<string>("RunKey").IsRequired().HasColumnType("TEXT");
                    b.Property<decimal>("SelectedConfidenceThreshold").HasColumnType("TEXT");
                    b.Property<string>("SelectionReason").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("SegmentsJson").IsRequired().HasColumnType("TEXT");
                    b.Property<int>("SourceCandidateCount").HasColumnType("INTEGER");
                    b.Property<string>("StrategyId").IsRequired().HasColumnType("TEXT");
                    b.Property<DateTime>("ToUtc").HasColumnType("TEXT");
                    b.Property<int>("WalkForwardFoldCount").HasColumnType("INTEGER");
                    b.Property<string>("WalkForwardMetricsJson").IsRequired().HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("EvaluationVersion");
                    b.HasIndex("ReplayRunId");
                    b.HasIndex("RunKey").IsUnique();
                    b.HasIndex("InstrumentId", "StrategyId", "HorizonSeconds", "CompletedAtUtc");
                    b.ToTable("ResearchEvaluationRunRecords");
                });

            modelBuilder.Entity("TradingBot.Persistence.RiskDecisionRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DecisionJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RiskDecisionRecords");
                });

            modelBuilder.Entity("TradingBot.Persistence.StrategyDecisionRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DecisionJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("StrategyDecisionRecords");
                });

            modelBuilder.Entity("TradingBot.Persistence.Trade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ClosedUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EntryPrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ExitPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OpenedUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Size")
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClosedUtc");

                    b.HasIndex("OpenedUtc");

                    b.HasIndex("Symbol");

                    b.ToTable("Trades");
                });
            modelBuilder.Entity("TradingBot.Persistence.CandidateLabelRecord", b =>
                {
                    b.HasOne("TradingBot.Persistence.ResearchCandidateRecord", "ResearchCandidate")
                        .WithMany("Labels")
                        .HasForeignKey("ResearchCandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("ResearchCandidate");
                });

            modelBuilder.Entity("TradingBot.Persistence.ResearchCandidateRecord", b =>
                {
                    b.Navigation("Labels");
                });
#pragma warning restore 612, 618
        }
    }
}
