// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TradingBot.Persistence;

#nullable disable

namespace TradingBot.Persistence.Migrations
{
    [DbContext(typeof(TradingBotDbContext))]
    partial class TradingBotDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("TradingBot.Persistence.AiAnalysisRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Context")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgentType");

                    b.HasIndex("Model");

                    b.HasIndex("PromptVersion");

                    b.HasIndex("TimestampUtc");

                    b.ToTable("AiAnalysisRecords");
                });

            modelBuilder.Entity("TradingBot.Persistence.AiApiUsageRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("CachedInputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FailureReason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("InputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("OutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TotalTokens")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AgentType");

                    b.HasIndex("Model");

                    b.HasIndex("Pattern");

                    b.HasIndex("PromptVersion");

                    b.HasIndex("RequestType");

                    b.HasIndex("Success");

                    b.HasIndex("Symbol");

                    b.HasIndex("TimestampUtc");

                    b.ToTable("AiApiUsageRecords");
                });

            modelBuilder.Entity("TradingBot.Persistence.BotSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StoppedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BotSessions");
                });

            modelBuilder.Entity("TradingBot.Persistence.Candle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Close")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("High")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Low")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Open")
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Timeframe")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Volume")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "Timeframe", "TimestampUtc")
                        .IsUnique();

                    b.ToTable("Candles");
                });

            modelBuilder.Entity("TradingBot.Persistence.ExitManagementRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BreakEvenActivated")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ClosedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntryBrokerOrderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FilledQuantity")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HighestPriceSinceEntry")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InitialEntryPrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InitialRiskPerShare")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InitialStopPrice")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OpenedUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrentProtectiveStop")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ProtectedQuantity")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProtectiveStopBrokerOrderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("TrailingActivated")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TrailingAtrMultiplier")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrailingAtrTimeframe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TradeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EntryBrokerOrderId")
                        .IsUnique();

                    b.HasIndex("ProtectiveStopBrokerOrderId");

                    b.HasIndex("State");

                    b.HasIndex("Symbol");

                    b.HasIndex("UpdatedUtc");

                    b.ToTable("ExitManagementRecords");
                });

            modelBuilder.Entity("TradingBot.Persistence.ExitStopAuditRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrokerOrderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CurrentAtr")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrentRMultiple")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntryBrokerOrderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExitManagementState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HighestPriceSinceEntry")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MarketPrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NewStop")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("OldStop")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TradeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BrokerOrderId");

                    b.HasIndex("EntryBrokerOrderId");

                    b.HasIndex("Symbol");

                    b.HasIndex("TimestampUtc");

                    b.HasIndex("TradeId");

                    b.ToTable("ExitStopAuditRecords");
                });

            modelBuilder.Entity("TradingBot.Persistence.ExecutionRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrokerExecutionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderRecordId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BrokerExecutionId")
                        .IsUnique();

                    b.ToTable("ExecutionRecords");
                });

            modelBuilder.Entity("TradingBot.Persistence.InstrumentRegistryRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AllowedDirectionsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("BrokerContractId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrokerPrimaryExchange")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigurationHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ConfiguredEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InstrumentId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("MarketDataTimeframesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaximumHoldingSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("MaximumPositionValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecurityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StatusChangedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusReason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StrategyIdsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("TradingRequested")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ConfiguredEnabled");

                    b.HasIndex("InstrumentId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("Symbol");

                    b.HasIndex("UpdatedAtUtc");

                    b.ToTable("InstrumentRegistryRecords");
                });

            modelBuilder.Entity("TradingBot.Persistence.InstrumentStatusTransitionRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FromStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InstrumentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ToStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentId");

                    b.HasIndex("TimestampUtc");

                    b.HasIndex("ToStatus");

                    b.ToTable("InstrumentStatusTransitionRecords");
                });

            modelBuilder.Entity("TradingBot.Persistence.MarketSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MarketSnapshots");
                });

            modelBuilder.Entity("TradingBot.Persistence.OrderRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrokerOrderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientOrderKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BrokerOrderId");

                    b.HasIndex("ClientOrderKey")
                        .IsUnique()
                        .HasFilter("ClientOrderKey <> ''");

                    b.ToTable("OrderRecords");
                });

            modelBuilder.Entity("TradingBot.Persistence.PatternDetection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DetectedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("PatternType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PatternType");

                    b.HasIndex("Symbol");

                    b.ToTable("PatternDetections");
                });

            modelBuilder.Entity("TradingBot.Persistence.PostTradeAnalysisRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("AboveVwap")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AiCriticAnalysisJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("AiConfidence")
                        .HasColumnType("TEXT");

                    b.Property<string>("AiDecision")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AiMarketAnalysisJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CommissionsFees")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ClosedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CriticDecision")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EntryPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutionDataJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ExitPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("FifteenMinuteTrend")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GrossProfitLoss")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HoldingDurationMinutes")
                        .HasColumnType("TEXT");

                    b.Property<string>("MarketRegime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MarketSnapshotJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MaximumAdverseExcursion")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MaximumFavorableExcursion")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NetProfitLoss")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OpenedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderDataJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PatternCandidateJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<string>("RiskDecision")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RiskDecisionJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SourceTradeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StrategyDecision")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StrategyDecisionJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TradeResult")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TradeResultJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AboveVwap");

                    b.HasIndex("AiDecision");

                    b.HasIndex("ClosedUtc");

                    b.HasIndex("FifteenMinuteTrend");

                    b.HasIndex("MarketRegime");

                    b.HasIndex("Pattern");

                    b.HasIndex("SourceTradeId");

                    b.HasIndex("Symbol");

                    b.ToTable("PostTradeAnalysisRecords");
                });

            modelBuilder.Entity("TradingBot.Persistence.RiskDecisionRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DecisionJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RiskDecisionRecords");
                });

            modelBuilder.Entity("TradingBot.Persistence.StrategyDecisionRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DecisionJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("StrategyDecisionRecords");
                });

            modelBuilder.Entity("TradingBot.Persistence.Trade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ClosedUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EntryPrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ExitPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OpenedUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Size")
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClosedUtc");

                    b.HasIndex("OpenedUtc");

                    b.HasIndex("Symbol");

                    b.ToTable("Trades");
                });
#pragma warning restore 612, 618
        }
    }
}
